server:
  service:
    type: LoadBalancer
  extraArgs:
    - --insecure=false
configs:
  credentialTemplates:
    ssh-creds:
      url: ssh://git@github.com/uche-madu
      sshPrivateKeySecret:
        name: ssh-key-secret
        key: sshPrivateKey

  repositories:
    deb-infra-repo:
      url: ssh://git@github.com/uche-madu/deb-infrastructure.git
      type: git
