airflow:
  # Airflow home directory
  # Used for mount paths
  airflowHome: /opt/airflow

  # Default airflow repository -- overridden by all the specific images below
  defaultAirflowRepository: apache/airflow

  # Default airflow tag to deploy
  defaultAirflowTag: "2.7.1"

  # Airflow version (Used to make some decisions based on Airflow Version being deployed)
  airflowVersion: "2.7.1"

  # Images
  images:
    airflow:
      # To be replaced automatically by the Github Actions CICD workflow
      # in the DEB Application repository
      repository: ~
      tag: ~
      # Specifying digest takes precedence over tag.
      digest: ~
      pullPolicy: Always

  # Add common labels to all objects and pods defined in this chart.
  labels:
    environment: dev

  executor: KubernetesExecutor

  # Provider Connections
  # https://airflow.apache.org/docs/helm-chart/stable/adding-connections-and-variables.html#connections-and-sensitive-environment-variables
  secret:
    - envName: "AIRFLOW_CONN_GCP"
      secretName: "airflow-gcp-connection"
      secretKey: "AIRFLOW_CONN_GCP"
    - envName: "AIRFLOW_CONN_POSTGRES"
      secretName: "airflow-db-connection-secret"
      secretKey: "AIRFLOW_CONN_POSTGRES"

  # Postgresql DB Connection  
  data:
    metadataSecretName: airflow-db-connection-secret

  # Git sync
  dags:
    gitSync:
      enabled: true
      repo: git@github.com:uche-madu/deb-application.git
      branch: main
      subPath: "dags"
      sshKeySecret: airflow-ssh-secret

      # Get info about known_hosts from here: 
      # https://airflow.apache.org/docs/helm-chart/stable/production-guide.html#knownhosts
      knownHosts: |
        github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
    
  enableBuiltInSecretEnvVars:
    AIRFLOW__CORE__FERNET_KEY: false
    AIRFLOW__WEBSERVER__SECRET_KEY: false
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: false
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: false
    AIRFLOW_CONN_AIRFLOW_DB: false
  
  fernetKeySecretName: "fernet-key-secret"
  
  webserverSecretKeySecretName: "airflow-webserver-secret"


  # Airflow webserver settings
  webserver:
    service:
      type: LoadBalancer
    
    # Create initial user.
    defaultUser:
      enabled: true
      role: Admin
      username: admin
      email: admin@example.com
      firstName: admin
      lastName: user
      password: admin

  postgresql:
    enabled: false
  
  pgbouncer:
    enabled: true

  redis:
    enabled: false

  workers:
    persistence:
      size: 5Gi
      
  # Airflow Triggerer Config
  triggerer:
    persistence:
      # Volume size for triggerer StatefulSet
      size: 5Gi

  logs:
    persistence:
      # Enable persistent volume for storing logs
      enabled: true
      # Volume size for logs
      size: 1Gi

  # To avoid issues with database migrations when deploying with ArgoCD
  # https://airflow.apache.org/docs/helm-chart/stable/index.html#installing-the-chart-with-argo-cd-flux-rancher-or-terraform
  createUserJob:
    useHelmHooks: false
    applyCustomEnv: false
  migrateDatabaseJob:
    useHelmHooks: false
    applyCustomEnv: false
    jobAnnotations:
          "argocd.argoproj.io/hook": Sync
