apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:uche-madu/deb-infrastructure.git
    path: argocd-app/monitoring
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - allowEmpty=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - Replace=true
      - ServerSideApply=true

