name: Terraform Workflow

on:
    push:
        branches:
            - main
            - develop
    pull_request:
        branches:
            - main
        paths:
            - 'terraform/**'
            - '.github/workflows/**'
            - '!**/README.md'
        types:
            - closed
    workflow_dispatch:
        inputs:
            destroy:
                description: 'Destroy the infrastructure'
                type: boolean
                required: true
                default: false

jobs:
    terraform:
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
                working-directory: ./terraform
        
        env:
            AIRFLOW_SSH_KEY_PRIVATE: ${{ secrets.AIRFLOW_SSH_KEY_PRIVATE }}

        permissions:
            contents: 'read'
            id-token: 'write'
    
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
        
        - id: 'auth'
          name: 'Authenticate to Google Cloud'
          uses: 'google-github-actions/auth@v1'
          with:
            # Replace with values from setup.sh
            workload_identity_provider: 'projects/734911192367/locations/global/workloadIdentityPools/deb-pool/providers/github-actions'
            service_account: 'deb-sa@wizeline-deb.iam.gserviceaccount.com'
    
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v2
          with: 
            terraform_version: '1.5.7'
            terraform_wrapper: true
    
        - name: Terraform Init
          id: init
          run: terraform init
    
        - name: Terraform Format
          id: fmt
          run: terraform fmt -check
    
        - name: Terraform Validate
          id: validate
          run: terraform validate
    
        - name: Terraform Plan
          id: plan
          run: |
            terraform plan \
            -var="airflow_ssh_key_private=${{ env.AIRFLOW_SSH_KEY_PRIVATE }}" \
            -no-color \
            -input=false
        
        # Add a comment to pull requests with plan results
        - name: Add Plan Comment
          if: github.event_name == 'pull_request'
          id: comment
          uses: actions/github-script@v6
          env:
            PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            script: |
              try {
                const issue_number = ${{ github.event.pull_request.number }};
                const owner = ${{ github.repository_owner }};
                const repo = ${{ github.repository }};
                const output = `...`;  // your existing output string

                if (issue_number && owner && repo) {
                  github.issues.createComment({
                    issue_number: issue_number,
                    owner: owner,
                    repo: repo,
                    body: output
                  });
                } else {
                  console.error("Missing required information for commenting.");
                }
              } catch (error) {
                console.error("An error occurred:", error);
              }

    
        - name: Terraform Apply
          if: github.event_name == 'pull_request' && github.event.pull_request.merged == 'true'
          run: |
            terraform apply \
            -var="airflow_ssh_key_private=${{ env.AIRFLOW_SSH_KEY_PRIVATE }}" \
            -input=false \
            -auto-approve 
    
        - name: Terraform Destroy (Manual Trigger)
          if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main' && github.event.inputs.destroy == 'true'
          run: terraform destroy -auto-approve