name: Terraform Workflow

on:
    pull_request:
        branches:
            - main
        paths:
            - 'terraform/**'
            - '.github/workflows/**'
            - '!**/README.md'
    
    workflow_dispatch:
        inputs:
            destroy:
                description: 'Destroy the infrastructure'
                type: boolean
                required: true
                default: false

jobs:
    terraform:
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
                working-directory: ./terraform

        # Add "id-token" with the intended permissions.
        permissions:
            contents: 'read'
            id-token: 'write'
    
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
        
        - id: 'auth'
          name: 'Authenticate to Google Cloud'
          uses: 'google-github-actions/auth@v1'
          with:
            # Replace with values from setup.sh
            workload_identity_provider: 'projects/734911192367/locations/global/workloadIdentityPools/deb-pool/providers/github-actions'
            service_account: 'deb-sa@wizeline-deb.iam.gserviceaccount.com'
    
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v2
          with: 
            terraform_version: '1.5.7'
            terraform_wrapper: true
    
        - name: Terraform Init
          run: terraform init
    
        - name: Terraform Format
          run: terraform fmt -check
    
        - name: Terraform Validate
          run: terraform validate
    
        - name: Terraform Plan
          id: plan
          run: terraform plan -no-color
          continue-on-error: true
        
        - name: Display Terraform Plan Output
          if: steps.plan.outcome == 'failure'
          run: echo "Terraform plan failed. Please review the logs"
    
        - name: Terraform Apply
          if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == 'true'
          run: terraform apply -auto-approve
    
        - name: Terraform Destroy (Manual Trigger)
          if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main' && github.event.inputs.destroy == 'true'
          run: terraform destroy -auto-approve
        
        - name: Upload Terraform logs
          if: always()
          uses: actions/upload-artifact@v3
          with:
            name: terraform-plan
            path: ./terraform.tfplan